### ISSUE TITLE
Re-Deploy to DO so we can define the `admin` account

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-analytics#6]
@LuchoTurtle as discussed. Please:

- [x] re-deploy the `analytics.dwyl.com` so we can configure the `admin` account.

**Comment by LuchoTurtle** [comment]
It's already deployed.

**Comment by nelsonic** [comment]
Yeah, I know you're fast like a Ninja! 🥷 
I couldn't be a maze architect in your dreams ... 😉

**Comment by nelsonic** [comment]
Anyone not getting the Inception ref, see: https://youtu.be/ZszlJQhj4aA
